# 这些是受支持的赞助模式平台

# 将 YuzakiKokuban 替换为您的 GitHub 用户名
github: [YuzakiKokuban]

# 自定义链接，将显示在“Sponsor”按钮的下拉菜单中
custom:
  - https://www.paypal.me/LangQin280
  - https://qr.alipay.com/fkx13433fi3skccvxkldn48
  - https://app.binance.com/qr/dplk879862a9139d41469d7f3f66a059c5e9
